### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by jensmoths** [google-developer-training/basic-android-kotlin-compose-training-affirmations#10]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6

**Describe the problem**
The printed text does not seem to correspond to the previous code.

**In which lesson and step of the codelab can this issue be found?**
Lesson "Generics, objects, and extensions", step 7, subtitle "Replace long object names using let()", step 6.

**How to reproduce?**
-

**Versions**
-

**Additional information**
-

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @jensmoths ,

Thank you for reaching out to us. The code snippet was updated:

![Screen Shot 2022-12-05 at 12 53 00 PM](https://user-images.githubusercontent.com/86437155/205778695-dabd28c9-3106-4c72-82f5-fdb87492c565.png)
