### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by EisaAlkhulaifi** [google-developer-training/basic-android-kotlin-compose-training-affirmations#11]
**https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6**

**Describe the problem**
The printQuiz function is missing the extension beginning "Quiz."

**In which lesson and step of the codelab can this issue be found?**
7. Use scope functions to access class properties and methods

**How to reproduce?**
Text needs to be corrected.

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @EisaAlkhulaifi 

Thank you for writing in with your concern.

The `printQuiz()` function is placed inside the `Quiz` class. It is not an extension function.

If you still believe this is an issue, please create a new issue with additional details explaining further.

Hope you are enjoying the course!

Regards.
