### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by williamFerrante** [google-developer-training/basic-android-kotlin-compose-training-affirmations#12]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon#4

**Describe the problem**
This is a minor typo problem. The page in the URL above notes we'll be creating an adaptive icon for the Tip Calculator app. I believe it should say Affirmations app instead of Tip Time app. 
**In which lesson and step of the codelab can this issue be found?**
Unit 3, pathway 2, step 5

**How to reproduce?**
N/A

**Versions**
1. What version of Android Studio are you using? Chipmunk 2021.2.1 Patch 2
3. What API level are you targeting? N/A

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by lixoten** [comment]
YES,,, the downloaded images belong to the tip calcaulator... we can use these but they are not the ones displayed in the codelab for Affirmations
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#5

**Comment by osuleymanova** [comment]
Hello @williamFerrante  ,

Thank you for reaching out to us and reporting the issue. The app name and the assets were updated:

![Screen Shot 2022-12-01 at 2 26 38 PM](https://user-images.githubusercontent.com/86437155/205182428-13cc7e36-e1f7-4735-b21f-633bcbf16194.png)
