### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by mwex42** [google-developer-training/basic-android-kotlin-compose-training-affirmations#14]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#4

**Describe the problem**
The text in the output box at the end of the page is incorrect, the output should be "3 of 10 answered."  The output in the example reads page "3 of 10".  There is another sample half way down the screen on the same page with a missing .

**In which lesson and step of the codelab can this issue be found?**
Step 5 (URL included above)

**How to reproduce?**
N/A, this is an example page

**Versions**
1. What version of Android Studio are you using? N/A
2. What API level are you targeting? N/A

**Additional information**
Just commenting on incorrect output shown from a sample app, may confuse some new developer

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @mwex42,

Thank you for reaching out and reporting the missing dot in several places. They were added and republished.
