### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by RoskamsY1** [google-developer-training/basic-android-kotlin-compose-training-affirmations#16]
**[Generics, objects, and Extensions](https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6)**

**Describe the problem**
In the codelab named above (URL Included) in lesson 7 (Use scope functions to access class properties and methods), under the title Replace long object names using let(), in step 3 there is this code: 
<code>fun printQuiz() {
    question1.let {
        println(it.questionText)
        println(it.answer)
        println(it.difficulty)
    }
    println()
    question2.let {
        println(it.questionText)
        println(it.answer)
        println(it.difficulty)
    }
    println()
    question3.let {
        println(it.questionText)
        println(it.answer)
        println(it.difficulty)
    }
    println()
}</code>

But then: still in lesson 7, and still under the same title, but in step 6, there is following output:
<code>
Quoth the raven ___
nevermore
MEDIUM

Quoth the raven ___
nevermore
MEDIUM

Quoth the raven ___
nevermore
MEDIUM
</code>

If you ask me, this is a copy paste error 😉

**UPDATE**
In the same lesson under the title Call an object's methods without a variable using apply(), the same copy paste error is made

**In which lesson and step of the codelab can this issue be found?**
Lesson 7 (Use scope functions to access class properties and methods), under Replace long object names using let(), in step 3 and 6, and under Call an object's methods without a variable using apply(), in step 2 and 4

**How to reproduce?**
by reading the text 

**codelab:** basic-android-kotlin-compose-generics
![Schermafbeelding_20221024_104622](https://user-images.githubusercontent.com/109538661/197486236-392e5d26-d185-4a65-9a80-642c24b5f9c6.png)
![Schermafbeelding_20221024_104655](https://user-images.githubusercontent.com/109538661/197486239-e936d7e7-1578-412b-a696-af8b5404e1a0.png)

**Comment by osuleymanova** [comment]
Hello @RoskamsY1,

Thank you for reaching out to us and reporting those typos. The code snippets are updated:

![Screen Shot 2022-12-05 at 12 53 00 PM](https://user-images.githubusercontent.com/86437155/205777458-c5b4758f-96a4-401f-b0ac-881681d4a280.png)

![Screen Shot 2022-12-05 at 1 09 50 PM](https://user-images.githubusercontent.com/86437155/205777598-2c43c3c2-4b94-4bf3-ba9a-9973c0624e46.png)
