### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by baardkrk** [google-developer-training/basic-android-kotlin-compose-training-affirmations#17]
**Name of the Codelab or Codelab URL**  
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#4

**Describe the problem**

The link to the foreground icon vector file is wrong. It points to an asset in the tip calculator codelab, but should point to an asset in the affirmation codelab.

Correct link: https://raw.githubusercontent.com/google-developer-training/basic-android-kotlin-compose-training-affirmations/main/app/src/main/res/drawable/ic_launcher_foreground.xml

**In which lesson and step of the codelab can this issue be found?**  
Lesson number 5: Dosnload new assets  
Step number: N/A

**How to reproduce?**  
Go to the codelab and reaffirm that the link for the ic_launcher_foreground.xml is pointing to the wrong asset.

**Versions**  
1. What version of Android Studio are you using? N/A  
2. What API level are you targeting? N/A  

**Additional information**  

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by baardkrk** [comment]
Duplicate of #1 and #2

**Comment by osuleymanova** [comment]
Hello @baardkrk ,

Thank you for reaching out to us and reporting the issue. The app name and  the assets were updated:

![Screen Shot 2022-12-01 at 2 26 38 PM](https://user-images.githubusercontent.com/86437155/205172778-3fe53af5-98b8-4d77-bb38-493427bd201c.png)
