### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by thequietsteve** [google-developer-training/basic-android-kotlin-compose-training-affirmations#18]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics

**Describe the problem**
This is just a typo. In the **Access a singleton object** section, the `StudentProgress` object is referred to as `Progress`.

> Because there's only one instance of `Progress` in existence at one time...

should be

> Because there's only one instance of `StudentProgress` in existence at one time...

**In which lesson and step of the codelab can this issue be found?**
Lesson 2 step 5.

**How to reproduce?**
N/A

**Versions**
N/A

**Additional information**
N/A

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @thequietsteve,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screenshot 2023-01-26 at 3 14 34 PM](https://user-images.githubusercontent.com/86437155/214971767-3babcb59-428f-4a75-99ca-b3de81316deb.png)
