### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by luovahulluus** [google-developer-training/basic-android-kotlin-compose-training-affirmations#19]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#3

**Describe the problem**
The instruction is to "Go back to the Project view and locate the background and foreground drawables: res > drawable > ic_launcher_background.xml and drawable-v26 > ic_launcher_foreground.xml." However, in Android Studio Dolphin, there is no drawable-v26 directory. The only ic_launcher_foreground.xml file is in the drawable-v24 directory. I did use the search function.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
[4. Adaptive Icons](https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#3)

**How to reproduce?**
What are the exact steps to reproduce the problem?
Just follow the instructions

**Versions**
1. What version of Android Studio are you using?
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

2. What API level are you targeting?
33

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by hhyeok1026** [comment]
I was curious about this too.
I looked up a few things and made a guess.

// VectorDrawable doc
https://developer.android.com/reference/android/graphics/drawable/VectorDrawable

**Looking at the above document,
To use VectorDrawable, api21 or higher is required.
And for the 'android:fillColor' option to be applied in ic_launcher_background.xml, it seems to be api24**

It is assumed that the folder automatically created by the IDE was drawable-v21 or drawable-24.
So maybe there was an auto-generated drawable-v24,

In the codelab description, 
the application of the adaptive icon is v26, 
so I guess it was explained in v26.

**Comment by johnshea** [comment]
Hi @luovahulluus @hhyeok1026 

Thank you for writing in about this issue and your steps to troubleshoot it.

The lesson content has been updated to reflect the steps while using the latest stable version of Android Studio so this issue has been addressed.

If you find any other issues, please do not hesitate to let us know.

Hope you are enjoying the course!

Regards.
