### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by giladze** [google-developer-training/basic-android-kotlin-compose-training-affirmations#20]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6

**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Replace long object names using let()
step 6
wrong answer on scream. you print qoustion number 1 for 3 times

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @giladze,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:
 
![Screen Shot 2022-12-05 at 12 53 00 PM](https://user-images.githubusercontent.com/86437155/205741281-ff74fdde-bd9a-4241-adc1-d23627235328.png)
