### ISSUE TITLE
Practice: Classes and Collections: Android Basics in Compose  

### ISSUE THREAD

**Issue by nav1s** [google-developer-training/basic-android-kotlin-compose-training-affirmations#23]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-classes-and-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-classes-and-collections#5

**In which task and step of the codelab can this issue be found?**
task 2 (step 5)

**Describe the problem**
The solution code for task 2 has ```EVENING``` value instead of the value ```NIGHT``` that was specified in the task description.

**Comment by osuleymanova** [comment]
Hello @nav1s ,
Thank you for reaching out to us. The Task 2 Solution code snippet is correct, but the typo in the previous section 5 Task 2 is fixed now. It's supposed to be EVENING value:

![Screen Shot 2022-11-30 at 2 15 49 PM](https://user-images.githubusercontent.com/86437155/204920549-45d10678-7762-4e5c-9d4c-b70860e2030f.png)
