### ISSUE TITLE
Android Compose Change the App Icon

### ISSUE THREAD

**Issue by bkrauth** [google-developer-training/basic-android-kotlin-compose-training-affirmations#25]
**Name of the Codelab or Codelab URL**
Change the App Icon
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-change-app-icon#5

**Describe the problem**
A clear and concise description of what the problem is.
The downloaded icon does not look like what is shown.
It shows more of a flower, but the downloaded icon is more of a bell.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Download: Lesson 5
Picture shown: Lesson 6, step 11

**How to reproduce?**
What are the exact steps to reproduce the problem?
Download from Lesson 5.
See picture in Lesson 6.

**Versions**
1. What version of Android Studio are you using? 2021.3.1 Patch 1 - Build #AI-213.7172.25.2113.9123335, built on September 29, 2022
2. What API level are you targeting? 31

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by sc-gds-lxl** [comment]
This has been resolved.
