### ISSUE TITLE
Android Compose Higher Order Functions with Collections

### ISSUE THREAD

**Issue by Yousaf128** [google-developer-training/basic-android-kotlin-compose-training-affirmations#26]
**Name of the Codelab or Codelab URL**

**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @Yousaf128 ,

Please provide the details of the issue you are facing, so that we can help you with troubleshooting.

**Comment by johnshea** [comment]
Hi @Yousaf128 

If you are still having an issue, please do not hesitate to create a new issue so we can address it.

Hope you are enjoying the course!

Regards.
