### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by DTselikis** [google-developer-training/basic-android-kotlin-compose-training-affirmations#28]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-add-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-add-scrollable-list#5

**Describe the problem**
When trying to add the Scaffold with the given syntax the IDE shows a "Content padding parameter it is not used" error.

**In which lesson and step of the codelab can this issue be found?**
Lesson 4, step 1 of "Display the list"

**How to reproduce?**
Add or copy and paste the code of the AffirmationApp function from the given step to your AffirmationApp implementation.

**Versions**
1. Android Studio Version: Android Studio Dolphin | 2021.3.1 Patch 1
2. Target API level: 33

**Additional information**
Tried with both the outdated dependencies version of the started code and the up-to-date versions.

**codelab:** basic-android-compose-training-add-scrollable-list

![image](https://user-images.githubusercontent.com/61058636/205058222-843c351d-409c-4c2e-888f-7bedba422882.png)

**Comment by osuleymanova** [comment]
Hello @DTselikis ,

Thank you for reaching out to us and providing the screenshot with the issue. You may omit the Scaffold  in your code:

<img width="1196" alt="Screen Shot 2022-12-01 at 3 38 41 PM" src="https://user-images.githubusercontent.com/86437155/205181860-b613fd81-d544-4ac8-8910-9eb180abee0c.png">
