### ISSUE TITLE
Android Compose Higher Order Functions with Collections

### ISSUE THREAD

**Issue by Vahlec** [google-developer-training/basic-android-kotlin-compose-training-affirmations#29]
**Name of the Codelab or Codelab URL**
More Kotlin Fundamentals - Kotlin Higher Order Functions with Collections

URL:
https://developer.android.com/codelabs/basic-android-kotlin-compose-higher-order-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-higher-order-functions#6

**Describe the problem**
It's not a mistake or problem, but is confusing. In the data collection used for the example, one entry has the name: Chocolate chip. When sortedBy is used on the collection name Chocolate Peanut Butter is place before Chocolate chip. The ordering can be corrected by changing the sortedBy lambda to it.name?.lowercase(). It would be nice for the lesson to explain why this is the case.

**In which lesson and step of the codelab can this issue be found?**
Android Basics with Compose
Unit 3: Display lists and use Material Design
Lesson number: 4 More Kotlin Fundamentals
Step number 7 sortedBy

**How to reproduce?**
Follow the lesson steps and use the names "Chocolate chip" and "Chocolate Peanut Butter" in the data collection

**Versions**
1. IntelliJ IDEA 2022.2.3 (Community Edition)
2. Target JVM version 1.8

**Additional information**
Just a request to add a bit more information about how alphabetically order works with sortedBy and capitalization.

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @Vahlec 

Thank you for writing in with this issue and how it could cause confusion.

The lesson has been updated and it will be republished in the near future.

Hope you are enjoying the course!

Regards.
