### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by stakhur** [google-developer-training/basic-android-kotlin-compose-training-affirmations#30]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6

**Describe the problem**
Incorrect output in the **Run your code to verify that everything works.**
A mistake because of the copy-paste.

**In which lesson and step of the codelab can this issue be found?**
Generics, objects, and extensions, Step number 7. 

**How to reproduce?**
Open the page. There is an incorrect information of the page:
```
6. Run your code to verify that everything works.

Quoth the raven ___
nevermore
MEDIUM

Quoth the raven ___
nevermore
MEDIUM

Quoth the raven ___
nevermore
MEDIUM
```

**Versions**
-

**Additional information**
-

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @stakhur,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screen Shot 2022-12-05 at 12 53 00 PM](https://user-images.githubusercontent.com/86437155/205740923-4b7c62e5-6cdf-4fac-b3f2-ec43e627588d.png)

**Comment by stakhur** [comment]
Cool. The same issue at the end of the same page (sorry not to report about this problem earlier in the issue).

4.
```
3 of 10 answered.
kotlin.Unit
Quoth the raven ___
nevermore
MEDIUM

Quoth the raven ___
nevermore
MEDIUM

Quoth the raven ___
nevermore
MEDIUM
```

**Comment by osuleymanova** [comment]
@stakhur,
Thanks! And that code snippet is updated as well:

![Screen Shot 2022-12-05 at 1 09 50 PM](https://user-images.githubusercontent.com/86437155/205743903-6e2b06e2-77ab-4265-8918-55930393d686.png)

**Comment by stakhur** [comment]
@osuleymanova ,

That is strange, but I see the same as before:

![image](https://user-images.githubusercontent.com/90437484/205752165-df136a9a-6350-461a-bbbd-ce788dd4fd06.png)

**Comment by osuleymanova** [comment]
@stakhur,
In 5-10 minutes please reload the page. If the page is not updated, let us know.

**Comment by stakhur** [comment]
@osuleymanova ,

Great job :).

Everything is perfect now, thank you very much!

**Comment by osuleymanova** [comment]
@stakhur ,
Most welcome. Happy coding!
