### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by LironCareto** [google-developer-training/basic-android-kotlin-compose-training-affirmations#31]
I cannot make it work. The description of the code modifications is too vague and I find myself randomly adding the progressText here and there, and obtaining the error "Unresolved reference: progressText" every time. To make things worse, this codelab does not have the reference code at the end, like others...

**Comment by osuleymanova** [comment]
Hello @LironCareto,

Thanks for reaching out to us and sharing your feedback. The content was reviewed and updated. Hopefully, it will resolve you issues and give a clear understanding.
