### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by kouroku-room** [google-developer-training/basic-android-kotlin-compose-training-affirmations#36]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-add-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%3Fhl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-add-scrollable-list#3

**Describe the problem**
The line breaks are not properly done.

**In which lesson and step of the codelab can this issue be found?**
"Create a list item card" - 5 - MainActivity.kt

**How to reproduce?**

**Versions**

**Additional information**
```
@Composable
fun AffirmationCard(affirmation: Affirmation, modifier: Modifier = Modifier) {Card(modifier = modifier.padding(8.dp), elevation = 4.dp) {
  }
}
```
->
```
@Composable
fun AffirmationCard(affirmation: Affirmation, modifier: Modifier = Modifier) {
  Card(modifier = modifier.padding(8.dp), elevation = 4.dp) {
  }
}
```
**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @kouroku-room 

Thank you for writing in and pointing out this issue.

It has been corrected and the lesson republished.

Hope you are enjoying the course!

Regards.
