### ISSUE TITLE
Android Compose Higher Order Functions with Collections

### ISSUE THREAD

**Issue by correabuscar** [google-developer-training/basic-android-kotlin-compose-training-affirmations#4]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-higher-order-functions?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-higher-order-functions#1

**Describe the problem**

> 2. Run your code. Notice that this inserts the name of the class, Cookie, and the property, name, into the string, followed by .name. The value of the name property isn't accessed.

Seems like the text `and the property, name, into the string,` should be removed, no?

**In which lesson and step of the codelab can this issue be found?**
`2. forEach() and string templates with lambdas`
under `Embed expressions in strings`

**Additional information**
![wut](https://user-images.githubusercontent.com/106607441/181995873-965bf42b-09fe-41aa-98f5-79ef7ce8a968.png)

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @correabuscar 

Thank you for writing in to bring this issue to our attention.

The wording in this part of the lesson has been corrected and the lesson will be republished in the near future.

Hope you are enjoying the course!

Regards.
