### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by HologramOfMe** [google-developer-training/basic-android-kotlin-compose-training-affirmations#41]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-add-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-add-scrollable-list#3

**Describe the problem**
I can't tell if this is a problem, or I just don't know enough.

I've notice in multiple codelabs a note like this "Note: It is a best practice to pass a modifier to every composable and set it to a default value."

...and usually it's followed by code which follows this advice like this
```
@Composable
fun AffirmationCard(affirmation: Affirmation, modifier: Modifier = Modifier) {
  Card(modifier = modifier.padding(8.dp), elevation = 4.dp) {
    Column {
    }
  }
}
```
You can see in the code above that the best practice advice is being followed. We are passing in a Modifier and then using it.
Cool, cool, cool, cool, cool. BUT, then, I often notice we quickly devolve into code like this...
```
@Composable
fun AffirmationCard(affirmation: Affirmation, modifier: Modifier = Modifier) {
  Card(modifier = Modifier.padding(8.dp), elevation = 4.dp) {
    Column {
      Image(
        painter = painterResource(affirmation.imageResourceId),
        contentDescription = stringResource(affirmation.stringResourceId)
      )
    }
  }
}
```
Now the passed in Modifier is no longer being referenced.

So my question is, is this simply a matter of not following the advice we are given, OR is there some technical reason why the course writers are doing this? 

**In which lesson and step of the codelab can this issue be found?**
Lesson 4 + step 6 and on.

**How to reproduce?**
Just read the codelab code.

**Versions**
1. What version of Android Studio are you using? not relevant
2. What API level are you targeting? not relevant

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by sc-gds-lxl** [comment]
The code and codelab have been updated.
