### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by paolobrogli** [google-developer-training/basic-android-kotlin-compose-training-affirmations#42]
**Name of the Codelab or Codelab URL**

Generics, objects, and extensions - TAB 7

**Describe the problem**
The code in the tab doesn't work: 

Var-property public open val progressText: String defined in Quiz cannot be overridden by val-property public abstract var progressText: String defined in ProgressPrintable

**Versions**
Kotlin playground

**Comment by johnshea** [comment]
Hi @paolobrogli 

Thank you for bringing this to our attention.

This will be fixed and published soon.

Hope you are enjoying the course!

Regards.
