### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by Rnscd** [google-developer-training/basic-android-kotlin-compose-training-affirmations#43]
**Name of the Codelab or Codelab URL**

https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6

**Describe the problem**

The property "progressText" is defined with "var" in the interface, instead of "val". The text above the code is also wrong, as it calls the property "progress" instead of "progressText"

**In which lesson and step of the codelab can this issue be found?**
7 + 2

**Comment by johnshea** [comment]
Hi @Rnscd

Thank you for bringing this to our attention.

This will be fixed and published soon.

Hope you are enjoying the course!

Regards.

**Comment by osuleymanova** [comment]
Fixed:
![Screenshot 2023-03-15 at 3 53 53 PM](https://user-images.githubusercontent.com/86437155/225461136-924b2ded-b57c-4c22-9777-34f4eb670060.png)
