### ISSUE TITLE
Android Compose Use Collections in Kotlin

### ISSUE THREAD

**Issue by Rnscd** [google-developer-training/basic-android-kotlin-compose-training-affirmations#44]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-collections#4

**Describe the problem**
Based on the text in this step, it's expected to see in the code an example of the "get()" method, but it just repeats the "subscript syntax" used in the step above. 
I believe the code should be "println(solarSystem.get("Theia"))"

**In which lesson and step of the codelab can this issue be found?**
5 + 7

**Comment by johnshea** [comment]
Hi @Rnscd

Thank you for bringing this to our attention.

This will be fixed and published soon.

Hope you are enjoying the course!

Regards.
