### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by Harman-Haiilo** [google-developer-training/basic-android-kotlin-compose-training-affirmations#45]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%3Fhl%3Den%26authuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics&hl=en#6

**Describe the problem**
A clear and concise description of what the problem is.
It's just a typo but a compiler will throw an error. A var property should actually be val.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson 7, step 2

**How to reproduce?**
interface ProgressPrintable {
    var ProgressText: String
}
This is the code block in codelab. Here ProgressText should be val.

**Versions**
1. What version of Android Studio are you using? - Kotlin playground 1.8.10 with JVM
2. What API level are you targeting?

**Additional information**

**codelab:**
 https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%3Fhl%3Den%26authuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics&hl=en
<img width="988" alt="Screenshot 2023-02-08 at 15 29 20" src="https://user-images.githubusercontent.com/110420484/217559276-3ddf2f24-bc37-4e71-8ee0-7e12f92b6a60.png">

**Comment by johnshea** [comment]
Hi @Harman-Haiilo 

Thank you for taking the time to document this issue.

It has been fixed and the change is now live in production.

Hope you are enjoying the course!

Regards.
