### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by ubugnu** [google-developer-training/basic-android-kotlin-compose-training-affirmations#46]
**Name of the Codelab or Codelab URL**
[https://developer.android.com/codelabs/basic-android-kotlin-compose-generics#6](https://developer.android.com/codelabs/basic-android-kotlin-compose-generics#6)

**Describe the problem**
`progressText` is defined as a `var` in the interface, but overriden as a `val` in `class Quiz: ProgressPrintable`.

**In which lesson and step of the codelab can this issue be found?**
More Kotlin fundamentals + step 2 (Generics, objects, and extensions).

**How to reproduce?**
copy-paste the code.

**Versions**
1. Not relevant
2. Not relevant

**Additional information**
None.

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @ubugnu 

Thank you for pointing out this issue.

It has been fixed and the change is live in production.

Hope you are enjoying the course!

Regards.
