### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by sgano** [google-developer-training/basic-android-kotlin-compose-training-affirmations#49]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-add-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-add-scrollable-list#3

**Describe the problem**
error when using items() in LazyColumn -- The compiler says it needs an Int not a List

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
[Add a scrollable list] + Step 4

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**
This code:

@Composable
private fun AffirmationList(affirmationList: List<Affirmation>, modifier: Modifier = Modifier) {
  LazyColumn {
    items(affirmationList){ affirmation ->
      AffirmationCard(affirmation)
    }
  }
}

Should be replaced by this code:
@Composable
private fun AffirmationList(affirmationList: List<Affirmation>, modifier: Modifier = Modifier) {
    LazyColumn {
        items(affirmationList.size){ affirmation ->
            AffirmationCard(affirmationList[affirmation])
        }
    }
}

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by sc-gds-lxl** [comment]
The code in the example is correct. The `items()` function you are referring to is [`LazyDsl.items()`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/LazyDsl.kt;l=78?q=LazyDsl.kt)

However, the function being referred to in the codelab (and found in the solution) is an extension function of `LazyListScope`. It's still defined in `LazyDsl`, but it is not the same and it can take a list as a parameter. See [`LazyListScope.items()`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/LazyDsl.kt;l=136?q=LazyDsl.kt).

To ensure you are using the correct function, make sure to have the following import:
`import androidx.compose.foundation.lazy.items`
