### ISSUE TITLE
Practice: Classes and Collections: Android Basics in Compose  

### ISSUE THREAD

**Issue by correabuscar** [google-developer-training/basic-android-kotlin-compose-training-affirmations#5]
Note that you used `EVENING` here
`val event6 = Event(title = "Check out latest Android Jetpack library", daypart = Daypart.EVENING, durationInMinutes = 45)`
which is here: https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-classes-and-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-classes-and-collections#6
aka on `7. Task 3`
However, `EVENING` would have to be added on previous step on `6. Task 2 Solution` which is here: https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-classes-and-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-classes-and-collections#5

ie.
![7evening](https://user-images.githubusercontent.com/106607441/181996794-fb809dc8-3f0f-487f-8d79-bd19c019f11e.png)
![6not](https://user-images.githubusercontent.com/106607441/181996796-62bb5ed3-0b22-4f63-8967-2c5efbd31134.png)

**Comment by correabuscar** [comment]
Oh, I see, my bad, I used the values from `5. Task 2` where there's `NIGHT` instead of `EVENING`, therefore, I saw it as missing the `EVENING` value in `7. Task 3`, but in fact, `NIGHT` on `5. Task 2` should be renamed from `NIGHT` to `EVENING`
here: 
https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-classes-and-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-classes-and-collections#4

![5night](https://user-images.githubusercontent.com/106607441/181996925-28e84a31-a170-496d-99f2-f2ab076d1069.png)

**Comment by correabuscar** [comment]
But also remember that `3. Task 1` here https://developer.android.com/codelabs/basic-android-kotlin-compose-practice-classes-and-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-practice-classes-and-collections#2
mentions `Night` in three places so that might need changing into `Evening` too?

![3night](https://user-images.githubusercontent.com/106607441/181997046-fea7d87a-ba0c-4e4a-8add-af1f4526a404.png)

**Comment by osuleymanova** [comment]
Hello @correabuscar,

Thank you for reaching out to us and providing so valuable description of the issue. The typo "night" is fixed, instead it's supposed to be "evening:"

![Screen Shot 2022-11-30 at 2 27 14 PM](https://user-images.githubusercontent.com/86437155/204922009-74e31dc4-c2fa-443c-abd1-dadcdedcc06b.png)

![Screen Shot 2022-11-30 at 2 15 49 PM](https://user-images.githubusercontent.com/86437155/204921623-74a9ca9f-9646-40d3-88bb-b97169024bbf.png)
