### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by BazRDI** [google-developer-training/basic-android-kotlin-compose-training-affirmations#52]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#7

**Describe the problem**
Missing parentheses in code sample.  If following the codelab trail, section 7.11 instantiated the 'Quiz' class.  In the code samples in section 8.4 and 8.5, the parentheses for instantiation are missing, causing the code to fail.

**In which lesson and step of the codelab can this issue be found?**
'ANDROID BASICS WITH COMPOSE>DISPLAY LISTS AND USE MATERIAL DESIGN>MORE KOTLIN FUNDAMENTALS', Lesson 2 'Generics, objects, and extensions', Step 8.

**How to reproduce?**
Follow the steps, using the code samples.

**Versions**
N/A

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @BazRDI 

Thank you for bringing this to our attention.

This will be fixed and published soon.

Hope you are enjoying these course!

Regards.
