### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by MegaC-C** [google-developer-training/basic-android-kotlin-compose-training-affirmations#54]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6

**Describe the problem**
2. In the ProgressPrintable interface, define a property named progress.
interface ProgressPrintable {
    var progressText: String
}

Problem: var used instead of val 
(in following code it is correct again)

**In which lesson and step of the codelab can this issue be found?**
unit3 pathway1 step7

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @MegaC-C,

Thank you for reaching out to us and bringing this typo to our attention. It is fixed and published soon:
![Screenshot 2023-03-16 at 8 53 57 AM](https://user-images.githubusercontent.com/86437155/225679048-06b08867-df3b-49f0-97e7-6b319828ac39.png)
