### ISSUE TITLE
Android Compose Generics Objects and Extensions: compiler error

### ISSUE THREAD

**Issue by elsbit** [google-developer-training/basic-android-kotlin-compose-training-affirmations#57]
**Name of the Codelab or Codelab URL**
[https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#7](url)

**Describe the problem**
Compiler error:
Unresolved reference: printProgressBar
Quiz.printProgressBar() should be removed so that it shows the implemented code output.

**In which lesson and step of the codelab can this issue be found?**
Lesson number:
8. Use scope functions to access class properties and methods

step number:
Replace long object names using let()
5. Call printQuiz()..

**Comment by fe60** [comment]
In [lesson 7](https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6) step 9/10 `printProgressBar()` gets converted from an extension function into an interface implementation.

In [lesson 8](https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#7) - _Replace long object names using let()_ (step 4 and 5) this conversion is not taken into account.
Code of step 5 resulting in the error mentioned above:
```
fun main() {
    Quiz.printProgressBar()
    val quiz = Quiz()
    quiz.printQuiz()
}
```
Correct code for step 5:
```
fun main() {
    val quiz = Quiz()
    quiz.printProgressBar()
    quiz.printQuiz()
}
```

Does it make sense to have a separate step 4 (needs to be fixed, too)?

**Comment by johnshea** [comment]
Hi @elsbit @fe60 

Thank you for writing in about these issues.

The lesson has been updated to address them and will be republished in the near future.

Hope you are enjoying the course!

Regards.
