### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by cedriclecocq** [google-developer-training/basic-android-kotlin-compose-training-affirmations#60]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?hl=fr&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%3Fhl%3Dfr%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#6

**Describe the problem**
Rewrite with interface using the code provided issue an error :
Var-property public open val progressText: String defined in Quiz cannot be overridden by val-property public abstract var progressText: String defined in ProgressPrintable

**In which lesson and step of the codelab can this issue be found?**
Lesson Android base concept with compose > Module 3 > Workshop 2 > Step 7

**How to reproduce?**
Just test in Kotlin Playground

**Versions**
1. What version of Android Studio are you using? Kotlin Playground
2. What API level are you targeting? N/A

**Additional information**
progressText can't be "var" in the interface and "val" in the class.
If progressText is "val" in the interface, there's no error.

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @cedriclecocq 

Thank you for writing in with this issue.

The lesson has been updated and republished.

Hope you are enjoying the course!

Regards.

**Comment by johnshea** [comment]
Fixed.
