### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by anidhamal** [google-developer-training/basic-android-kotlin-compose-training-affirmations#7]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#2

**Describe the problem**
`Enum constants are placed inside the constructor, separated by a comma.` 
I think this should be within the curly braces rather than constructor.

**In which lesson and step of the codelab can this issue be found?**
Generics, Objects & Extensions + step 3

**How to reproduce?**
This is the issue with the statement inside the codelab.

**Versions**
1. What version of Android Studio are you using? N/A
3. What API level are you targeting? N/A

**Additional information**
We get error if we try to add constants within enum class constructor.

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @anidhamal 

Thank you for writing in and bringing this issue to our attention.

The lesson has been corrected and will be republished in the near future.

Hope you are enjoying the course!

Regards.
