### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by jsmecha** [google-developer-training/basic-android-kotlin-compose-training-affirmations#70]
**Name of the Codelab or Codelab URL**

**Describe the problem**
There is no "headlineSmall" stylein typography for card text

**In which lesson and step of the codelab can this issue be found?**
Lesson3. Add a list to your app 
step 9

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @jsmecha 

Thank you for writing in with your issue.

As you did not provide any code or screenshots it is hard to know exactly what you typed and tried.

I can confirm that using `MaterialTheme.typography.headlineSmall` does work as intended while working through the codelab.

If you would like, please make sure you have the latest release version of Android Studio and the latest code from the repo and try working through the lesson again.

If you still have an issue, create a new issue and provide as much details, code, screenshots to fully demonstrate the problem so we can help you further.

Hope you are enjoying the course!

Regards.
