### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by sanyamj-081** [google-developer-training/basic-android-kotlin-compose-training-affirmations#71]
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#1

I am unable to get a desired output.

Lesson name : 
Generics, objects, and extensions
<img width="556" alt="Screenshot 2023-05-29 155217" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-affirmations/assets/104319672/027d11bb-56a4-4c1f-9ba1-09afcc2a6fe4">

**Comment by Ninidze1** [comment]
"Your Question class doesn't have any constructor parameters; instead, you declared them inside the class. I suggest moving those parameters up to the constructor, like this:
`class Question<T>(
    val questionText: String,
    val answer: Int,
    val difficulty: String
)`

**Comment by johnshea** [comment]
Hi @sanyamj-081 

As your issue has been resolved I am closing this issue.

@Ninidze1 Thank you for helping out to get them unblocked.

Hope you both are enjoying the course!

Regards.
