### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by TheTiinko** [google-developer-training/basic-android-kotlin-compose-training-affirmations#72]
**Name of the Codelab or Codelab URL**
Codelab: Add a Scrollable List
Chapter: Add a list to your app

**Describe the problem**
When creating a composable function  AffirmationList with LazyColumn child the items method needs a affirmationList.size (Int) argument and the "affirmation = affirmation" code snippet in the AffirmationCard function call needs to be changed to "affirmation = affirmationList[affirmation]" because item needs to be a Int type which represents index of the elements of the list provided as a argument in items method call.

**In which lesson and step of the codelab can this issue be found?**
Lesson: Create the list
Step: 6

**How to reproduce?**
Code that didn't work:

 LazyColumn(modifier = modifier) {
        items(affirmationList) { affirmation ->
            AffirmationCard(
                affirmation = affirmation,
                modifier = Modifier.padding(8.dp)
            )
        }
    }

Code that worked:

LazyColumn(modifier = modifier) {
        items(affirmationList.size) { affirmation->
            AffirmationCard(
                affirmation = affirmationList[affirmation],
                modifier = Modifier.padding(8.dp)
            )
        }
    }

**Versions**
1. What version of Android Studio are you using? Android Studio Flamingo | 2022.2.1 Patch 2 AI-222.4459.24.221.10121639
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by EzeGmnz** [comment]
Hey! just import this:
`import androidx.compose.foundation.lazy.items`

and you'll get it working. 
The course description is missing this 🥴

**Comment by johnshea** [comment]
Hi @TheTiinko 

Thank you for writing in with your issue.

As another student pointed out, you need to include `import androidx.compose.foundation.lazy.items` so the correct function will be called.

@EzeGmnz Thank you for providing the information they needed to get unblocked. Your help is appreciated.

Hope you are both enjoying the course!

Regards.
