### ISSUE TITLE
Android Compose Add a Scrollable List

### ISSUE THREAD

**Issue by KuhliusMuh** [google-developer-training/basic-android-kotlin-compose-training-affirmations#77]
[**L**](https://developer.android.com/codelabs/basic-android-kotlin-compose-training-add-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-training-add-scrollable-list#0)

Downloading the Project and importing it to Android Studio either results in an error (ClassDefFoundError: org/gradle/internal/impldep/com/google/common/collect/Lists) and/or "Add Configuration..." being written where normally "App" would be (next to where the emulator can be chosen).

**In which lesson and step of the codelab can this issue be found?**
1 + 6.

**How to reproduce?**
Just download and import the project (:

**Versions**
1. What version of Android Studio are you using? Android Studio Dolphin | 2021.3.1 Patch 1
2. What API level are you targeting? Pixel 5 API 31

**Additional information**

Thanks for helping!

**codelab:** basic-android-compose
![Error](https://github.com/google-developer-training/basic-android-kotlin-compose-training-affirmations/assets/133795874/9201dc53-4aeb-45b7-a2d7-897854238d71)
-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @KuhliusMuh 

Thank you for writing in with your issue.

I would suggest downloading and installing the latest stable version of Android Studio and trying again.

I downloaded the code and used "Android Studio Flamingo | 2022.2.1 Patch 2" with an emulator "Pixel 5 API 31" without any issues.

If you try that and still have an issue, please create a new issue so we can troubleshoot further.

Hope you are enjoying the course!

Regards.
