### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by AzamatZhapalakov** [google-developer-training/basic-android-kotlin-compose-training-affirmations#78]
[Unit 3: Display lists and use Material Design](https://developer.android.com/courses/android-basics-compose/unit-3)

An example is given
fun main() {
    Quiz.printProgressBar()
    val quiz = Quiz()
    quiz.printQuiz()
}

Must be
fun main() {
    Quiz().printProgressBar()
    val quiz = Quiz()
    quiz.printQuiz()

[**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.](https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#7)

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @AzamatZhapalakov 

Thank you for writing in concerning this issue.

The lesson has been updated and will be republished in the near future.

Hope you are enjoying the course!

Regards.
