### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by DeocBrut** [google-developer-training/basic-android-kotlin-compose-training-affirmations#79]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-generics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-generics#1

**Describe the problem**
When you run the code as the codelab suggests, then it returns an error for each of the values in the main(), because these variables are "never used".

**In which lesson and step of the codelab can this issue be found?**
Lesson number 2+ step number 6.

**How to reproduce?**
Just follow the codelab, or easier is to copy the code in steps 4 and 5 and then run the code like step 6 says.

**Versions**
1. What version of Android Studio are you using? - Kotlin playground online
2. What API level are you targeting? - N/A

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list
![Kotlin Playground - unit3 - part 2 - steps 4 to 6 ](https://github.com/google-developer-training/basic-android-kotlin-compose-training-affirmations/assets/107075275/7e509a99-2539-4502-a963-7fcc3a174d7e)

**Comment by johnshea** [comment]
Hi @DeocBrut 

Thank you for writing in with your issue.

The yellow circle with the "!" are warnings and not errors. An error shows as a red circle with the "!".

It is acceptable to see the yellow circle with the "!" as the lesson is building up slowly and it is correctly that they have not been used.

Note - The lesson does suggest that you use the Android Kotlin Playground which is found at https://developer.android.com/training/kotlinplayground.

Hope you are enjoying the course!

Regards.
