### ISSUE TITLE
Android Compose Generics Objects and Extensions

### ISSUE THREAD

**Issue by kofi-k** [google-developer-training/basic-android-kotlin-compose-training-affirmations#8]
**Name of the Codelab or Codelab URL**
Generics, objects, and extensions

**Describe the problem**
A clear and concise description of what the problem is.
Output of the code shown in snippet does not match the code's written println statement. 

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
Lesson 5, step 5 to 6 

**How to reproduce?**
What are the exact steps to reproduce the problem?
Steps.
1. Follow the codelab from lesson 2 through to lesson 5
2. Run the code generated by far i.e step 5 in lesson 5
3. Output of the code in real time is not as shown in step 6's code output snippet.

**Versions**
1. What version of Android Studio are you using?
4. What API level are you targeting?

**Additional information**

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by osuleymanova** [comment]
Hello @kofi-k,

Thanks for reaching out to us and sharing your concern. In fact, the step-by-step instructions and the output in the code snippet are consistent:

![Screenshot 2023-01-26 at 3 21 14 PM](https://user-images.githubusercontent.com/86437155/214972818-e751fe25-8593-483d-b988-248d67cb894e.png)
