### ISSUE TITLE
Question for "Android Compose Add a Scrollable List"

### ISSUE THREAD

**Issue by diskostu** [google-developer-training/basic-android-kotlin-compose-training-affirmations#80]
**Name of the Codelab or Codelab URL**
https://developer.android.com/codelabs/basic-android-kotlin-compose-training-add-scrollable-list

**Describe the problem**
Just a question: in the `Text` composable, loading the text is achieved by
```kotlin
Text(text = LocalContext.current.getString(affirmation.stringResourceId))
```
Why is not this code used:
```kotlin
Text(text = stringResource(id = affirmation.stringResourceId))
```
What are the internal differences? Are there any benefits by using the first one? Maybe performance?

**In which lesson and step of the codelab can this issue be found?**
Step 3 (add a list to your app)

**Versions**
Android Studio Hedgehog | 2023.1.1 Canary 10
Build #AI-231.9011.34.2311.10366083, built on June 22, 2023
Runtime version: 17.0.7+0-b2043.56-10353782 amd64

**codelab:** basic-android-compose-training-add-scrollable-list

**Comment by johnshea** [comment]
Hi @diskostu 

Thank you for writing in with your question.

They are actually both calling the same code in the `Resources.java` file.

If you drill down in Android Studio on each statement they will end up at the same place in the code.

Hope you are enjoying the course!

Regards.
