### ISSUE TITLE
Practice: Classes and Collections: Android Basics in Compose  

### ISSUE THREAD

**Issue by williamFerrante** [google-developer-training/basic-android-kotlin-compose-training-affirmations#9]
Class is great! Here's a MINOR issue. In the practice for classes and collections, task 2 says to define the enum Daypart as having NIGHT. In task 3, one of the events assigns daypart as Daypart.EVENING. Again, thanks for these great classes.

**Comment by osuleymanova** [comment]
Hello @williamFerrante,
We appreciate your feedback and the issue report. The typo in the Task 2 is fixed:

![Screen Shot 2022-11-30 at 2 15 49 PM](https://user-images.githubusercontent.com/86437155/204920997-35ee882e-1425-4d6f-bc7c-a69b5fe1abac.png)
